### ISSUE TITLE
Could you include mononoki

### ISSUE THREAD

**Issue by phadej** [knuesel/mono-math#1]
https://github.com/madmalik/mononoki got a release just few days ago. It *should* have nice math support (it is used in https://plfa.github.io/), but it would be nice to see the comparison.

I love this site. Thanks for making it!

**Comment by sijow** [comment]
Thanks! Mononoki is now included. Note that the version shown on the site is incorrect (the font metadata says 1.001 but it's actually 1.3, cf https://github.com/madmalik/mononoki/issues/75). It's a very nice font (though the coverage of math symbols seems rather small for now), thanks for sharing.
